# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      # Prefix all commit messages with "fix: "
      # This will ensure semanatic-release will pick up the commit messages and bump the version for npm
      prefix: 'fix'
    groups:
      # Make all minor and patch security updates go into one PR
      security-updates:
        applies-to: security-updates
        update-types:
          - 'patch'
          - 'minor'
      # Make all minor and patch version updates go into one PR
      version-updates:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
