name: Changelog and version updated

on: pull_request

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch master branch
        run: |
          git fetch origin master:master

      - name: Install jq for JSON processing
        run: sudo apt-get install -y jq

      - name: Check that changelog is updated
        run: |
          if ! git diff --name-only master | grep -q '^CHANGELOG.md$'; then
            echo "Error: CHANGELOG.md has not been updated."
            exit 1
          fi
