name: 'Tag and NPM publish'

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: 'Setup, and publish'
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out the repo'
        uses: actions/checkout@v4

      - name: 'Set up Node'
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 'lts/*'
          check-latest: true

      - name: 'Build'
        run: |
          npm ci
          npm run build

      - name: 'Publish to NPM'
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create tag
        run: |
          version=$(jq -r '.version' package.json)
          tag="v$version"
          echo "Creating tag: $tag"

          git tag "$tag"
          git push origin "$tag"
