name: Unit/Integration tests

on: pull_request

jobs:
  run-unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/Iron'
          check-latest: true

      - name: Install all dependencies
        run: |
          npm ci

      - name: Run unit tests
        run: |
          npm run test
